### Patataprint
### Configuration 

# Le thème à utiliser
theme: "amauryhamon"

# Le titre du document
title: Browsing, Gathering, Contextualizing	 # &nbsp; = espace insécable, <br class="breakprint"> produit un saut uniquement en version print

# Le sous-titre éventuel du document
subtitle: "Online tools for collaborative research and knowledge-making, cultivating alternative creative practices"

# Votre nom
name: Amaury Hamon

# L’année, par ex. : 2021 – 2022
year: 2023 – 2024 

# Votre diplôme, par ex. : DNA Design
diploma: Master HES-So en Design

# Le mention du diplôme, par ex. : Mention Design graphique Multimédia
mention: Orientation Master en Media Design # <br class="breakprint"> produit un saut uniquement en version print

# votre école
ecole: Haute École d'art et de design – Genève (HEAD)

# Votre pôle éventuel, par ex. : Pôle Nouveaux médias
# Pôle Image, édition &amp<br class="breakprint"> dessin de caractères
pole: 

# Le nom du fichier pdf généré, par ex. : titre-du-document--prenom-nom.pdf
pdf: "browsing-gathering-contextualizing--amaury-hamon"

# Structure du contenu (= sommaire)
parts:
  - title: Prefatory Note
    file : content/text/0.prefatorynote.md
    template : default
  
  - title: Introduction
    file: content/text/1.intro.md
    template: default
  
  - title: Exploring Visual Research Online
    file: content/text/2.artinprinting.md
    template: default
   
  - title: Pictorial Composition
    file: content/text/3.pictorial.md
    template: default
   
  - title: Type Composition
    file: content/text/4.type.md
    template: default
   
  - title: Conclusion
    file: content/text/5.conclusion.md
    template: default
   
  - title: Appendices
    file: content/text/6.annexes.md
    template: appendices
   
  # - title: Interview
  #   file: content/text/7.1.entretiens.md
  #   template: interview
  # create a parts Interview and inside, nest each entry with their title, template and file
  - title: "Interview: Gemma Copeland"
    file: content/text/7.itw-gemma-copeland.md
    template: interview
  - title: "Interview: Lucas Erin"
    file: content/text/7.itw-lucas-erin.md
    template: interview
  - title: "Interview: Florian Hilt"
    file: content/text/7.itw-florian-hilt.md
    template: interview
  - title: "Interview: Frederik Mahler-Andersen"
    file: content/text/7.itw-frederik-mahler-andersen.md
    template: interview
  - title: "Interview: Jonas Pelzer"
    file: content/text/7.itw-jonas-pelzer.md
    template: interview
  - title: "Interview: Émilie Pillet"
    file: content/text/7.itw-emilie-pillet.md
    template: interview
  - title: "Interview: Daniel Robert Prieto"
    file: content/text/7.itw-daniel-robert-prieto.md
    template: interview
  - title: "Interview: Aurélie Vial"
    file: content/text/7.itw-aurelie-vial.md
    template: interview
  - title: "Interview: Baker Wardlaw"
    file: content/text/7.itw-baker-wardlaw.md
    template: interview


  # - title: "Interview: Lucas Erin"
  #   file: content/text/7.1.entretiens.md
  #   template: interview

  # - title: "Interview: Aurélie Vial"
  #   file: content/text/7.1.entretiens.md
  #   template: interview

  - title: Glossary
    file: content/text/8.glossaire.md
    template: references
   
  - title: References
    file: content/text/9.references.md
    template: references
   
  - title: Acknowledgements
    file: content/text/10.remerciements.md
    template: thanks